services:
  front:
    container_name: music-front
    image: music-front
    build:
      context: ..
      dockerfile: docker/Dockerfile.front
    environment:
      PORT: 80
    ports:
      - "4200:80"